name: model-morpher
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - pandas
  - tqdm

  # PyTorch + CUDA (adjust cuda version to your driver)
  - pytorch=2.9.1
  - torchvision=0.24.1
  - pytorch-cuda=12.8  # if using nvidia GPU with CUDA 12.8 (check README.md if issues to pip install)
  - pytorch3d=0.7.9    # if available for your platform; otherwise install via pip below

  # Geometry / SDF / 3D
  - trimesh
  - mesh-to-sdf
  - open3d
  - pyrender

  # Visualisation
  - pyvista
  - pyvistaqt
  - vtk
  - matplotlib

  # Qt / GUI
  - pyqt

  # BrainGlobe
  - brainglobe-atlasapi
  - brainglobe-space


  - pip
  - pip:
      - pytorch-volumetric

